local gameInfo = {
    ["Name"] = "Chess",
    ["Version"] = "0.0.1",
    ["Creators"] = {"Bertie","Zaine"}
}

local defaultSetup = {
    [1] = {
        ["a"] = "black rook",
        ["b"] = "black knight",
        ["c"] = "black bishop",
        ["d"] = "black queen",
        ["e"] = "black king",
        ["f"] = "black bishop",
        ["g"] = "black knight",
        ["h"] = "black rook",
    },
    [2] = {
        ["a"] = " ",
        ["b"] = " ",
        ["c"] = " ",
        ["d"] = " ",
        ["e"] = " ",
        ["f"] = " ",
        ["g"] = " ",
        ["h"] = " ",
    },
    [3] = {
        ["a"] = " ",
        ["b"] = " ",
        ["c"] = " ",
        ["d"] = " ",
        ["e"] = " ",
        ["f"] = " ",
        ["g"] = " ",
        ["h"] = " ",
    },
    [4] = {
        ["a"] = " ",
        ["b"] = " ",
        ["c"] = " ",
        ["d"] = " ",
        ["e"] = " ",
        ["f"] = " ",
        ["g"] = " ",
        ["h"] = " ",
    },
    [5] = {
        ["a"] = " ",
        ["b"] = " ",
        ["c"] = " ",
        ["d"] = " ",
        ["e"] = " ",
        ["f"] = " ",
        ["g"] = " ",
        ["h"] = " ",
    },
    [6] = {
        ["a"] = " ",
        ["b"] = " ",
        ["c"] = " ",
        ["d"] = " ",
        ["e"] = " ",
        ["f"] = " ",
        ["g"] = " ",
        ["h"] = " ",
    },
    [7] = {
        ["a"] = " ",
        ["b"] = " ",
        ["c"] = " ",
        ["d"] = " ",
        ["e"] = " ",
        ["f"] = " ",
        ["g"] = " ",
        ["h"] = " ",
    },
    [8] = {
        ["a"] = "white rook",
        ["b"] = "white knight",
        ["c"] = "white bishop",
        ["d"] = "white queen",
        ["e"] = "white king",
        ["f"] = "white bishop",
        ["g"] = "white knight",
        ["h"] = "white rook",
    },
}

local funkyTestSetup = {
    [1] = {
        ["a"] = "black knight",
        ["b"] = "black bishop",
        ["c"] = "black rook",
        ["d"] = "black queen",
        ["e"] = "black king",
        ["f"] = "black rook",
        ["g"] = "black bishop",
        ["h"] = "black knight",
    },
    [2] = {
        ["a"] = " ",
        ["b"] = " ",
        ["c"] = " ",
        ["d"] = " ",
        ["e"] = " ",
        ["f"] = " ",
        ["g"] = " ",
        ["h"] = " ",
    },
    [3] = {
        ["a"] = " ",
        ["b"] = " ",
        ["c"] = " ",
        ["d"] = " ",
        ["e"] = " ",
        ["f"] = " ",
        ["g"] = " ",
        ["h"] = " ",
    },
    [4] = {
        ["a"] = " ",
        ["b"] = " ",
        ["c"] = " ",
        ["d"] = " ",
        ["e"] = " ",
        ["f"] = " ",
        ["g"] = " ",
        ["h"] = " ",
    },
    [5] = {
        ["a"] = " ",
        ["b"] = " ",
        ["c"] = " ",
        ["d"] = " ",
        ["e"] = " ",
        ["f"] = " ",
        ["g"] = " ",
        ["h"] = " ",
    },
    [6] = {
        ["a"] = " ",
        ["b"] = " ",
        ["c"] = " ",
        ["d"] = " ",
        ["e"] = " ",
        ["f"] = " ",
        ["g"] = " ",
        ["h"] = " ",
    },
    [7] = {
        ["a"] = " ",
        ["b"] = " ",
        ["c"] = " ",
        ["d"] = " ",
        ["e"] = " ",
        ["f"] = " ",
        ["g"] = " ",
        ["h"] = " ",
    },
    [8] = {
        ["a"] = "white knight",
        ["b"] = "white bishop",
        ["c"] = "white rook",
        ["d"] = "white queen",
        ["e"] = "white king",
        ["f"] = "white rook",
        ["g"] = "white bishop",
        ["h"] = "white knight",
    },
}